# Generated by Django 5.0.4 on 2024-09-26 18:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id_chauffeur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_chauffeur', models.CharField(max_length=200)),
                ('cin', models.CharField(max_length=20, unique=True)),
                ('permis', models.CharField(max_length=50, unique=True)),
                ('contact', models.CharField(max_length=15)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_maj', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
