# Generated by Django 5.0.4 on 2024-09-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperative', '0002_chauffeur_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chauffeur',
            options={'verbose_name': 'Chauffeur'},
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='chauffeurs/'),
        ),
    ]
