# Generated by Django 5.0.4 on 2024-09-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperative', '0004_chauffeur_age_chauffeur_disponibilite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chauffeur',
            name='img',
            field=models.TextField(),
        ),
    ]
