# Generated by Django 5.0.4 on 2024-09-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperative', '0005_alter_chauffeur_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='img64',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='chauffeurs/'),
        ),
    ]
