# Generated by Django 5.0.4 on 2024-09-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperative', '0006_chauffeur_img64_alter_chauffeur_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chauffeur',
            name='img64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
