# Generated by Django 5.0.4 on 2024-09-27 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperative', '0007_alter_chauffeur_img64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chauffeur',
            name='img64',
        ),
    ]
