# Generated by Django 5.0.4 on 2024-09-28 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperative', '0010_cooperative'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCoop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=15, null=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cooperative.cooperative')),
            ],
            options={
                'verbose_name': 'Contact Cooperative',
            },
        ),
    ]
