# Generated by Django 5.0.4 on 2024-09-29 10:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperative', '0012_remove_cooperative_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id_transport', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=10)),
                ('capacite', models.IntegerField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='transports/')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cooperative.chauffeur')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cooperative.cooperative')),
            ],
            options={
                'verbose_name': 'Transport',
            },
        ),
    ]
