# Generated by Django 5.1 on 2024-10-04 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperative', '0015_rename_id_typetransport_typetransport_id_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transport',
            old_name='typeTransport',
            new_name='type',
        ),
    ]
