# Generated by Django 5.1 on 2024-10-04 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperative', '0016_rename_typetransport_transport_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transport',
            old_name='type',
            new_name='typeTransport',
        ),
    ]
