# Generated by Django 5.1 on 2024-10-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperative', '0017_rename_type_transport_typetransport'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='statut',
            field=models.CharField(default='aucun', max_length=30),
            preserve_default=False,
        ),
    ]
