# Generated by Django 5.1 on 2024-10-15 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperative', '0018_transport_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatutTransport',
            fields=[
                ('id_statut', models.AutoField(primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Statut Transport',
            },
        ),
        migrations.AlterField(
            model_name='transport',
            name='statut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cooperative.statuttransport'),
        ),
    ]
