# Generated by Django 5.1 on 2024-10-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperative', '0019_statuttransport_alter_transport_statut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statuttransport',
            old_name='id_statut',
            new_name='id_statut_bus',
        ),
        migrations.RemoveField(
            model_name='statuttransport',
            name='intitule',
        ),
        migrations.AddField(
            model_name='statuttransport',
            name='intitule_statut_bus',
            field=models.CharField(default='aucun', max_length=30),
            preserve_default=False,
        ),
    ]
