# Generated by Django 5.0.4 on 2024-09-28 07:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCoop',
            fields=[
                ('id_adminCoop', models.AutoField(primary_key=True, serialize=False)),
                ('nom_admin', models.CharField(max_length=200, null=True)),
                ('cin', models.CharField(max_length=20, null=True, unique=True)),
                ('identifiant', models.CharField(max_length=100, null=True, unique=True)),
                ('mdp', models.CharField(max_length=100, null=True, unique=True)),
                ('mdp2', models.CharField(max_length=100, null=True, unique=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Admin Cooperative',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('nom_client', models.CharField(max_length=200, null=True)),
                ('cin', models.CharField(max_length=20, null=True, unique=True)),
                ('contact', models.CharField(max_length=15, null=True)),
                ('identifiant', models.CharField(max_length=100, null=True, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('mdp', models.CharField(max_length=100, null=True, unique=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('img', models.ImageField(blank=True, null=True, upload_to='Clients/')),
            ],
            options={
                'verbose_name': 'Client',
            },
        ),
    ]
