# Generated by Django 5.0.4 on 2024-09-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincoop',
            name='date_maj',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='client',
            name='date_maj',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='date_maj',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
