# Generated by Django 5.1 on 2024-10-04 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_admincoop_date_maj_client_date_maj_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superadmin',
            options={'verbose_name': 'Super admin'},
        ),
    ]
