# Generated by Django 5.0.4 on 2024-09-28 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Axe',
            fields=[
                ('id_axe', models.AutoField(primary_key=True, serialize=False)),
                ('cardinal', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Axe',
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id_ville', models.AutoField(primary_key=True, serialize=False)),
                ('nom_ville', models.CharField(max_length=100)),
                ('id_axe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voyage.axe')),
            ],
            options={
                'verbose_name': 'Ville',
            },
        ),
    ]
