# Generated by Django 5.0.4 on 2024-09-28 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voyage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ville',
            old_name='id_axe',
            new_name='axe',
        ),
    ]
