# Generated by Django 5.0.4 on 2024-09-29 10:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_admincoop_date_maj_client_date_maj_and_more'),
        ('Cooperative', '0013_transport'),
        ('Voyage', '0002_rename_id_axe_ville_axe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gare',
            fields=[
                ('id_gare', models.AutoField(primary_key=True, serialize=False)),
                ('nom_gare', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('img_gare', models.ImageField(blank=True, upload_to='Gares/')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voyage.ville')),
            ],
            options={
                'verbose_name': 'Gare',
            },
        ),
        migrations.CreateModel(
            name='ContactGare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=20)),
                ('gare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voyage.gare')),
            ],
            options={
                'verbose_name': 'Contact gare',
            },
        ),
        migrations.CreateModel(
            name='Itineraire',
            fields=[
                ('id_itineraire', models.AutoField(primary_key=True, serialize=False)),
                ('distance', models.IntegerField()),
                ('duree', models.IntegerField()),
                ('tarif', models.IntegerField()),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('gare_arrivee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gare_arrivee', to='Voyage.gare')),
                ('gare_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gare_depart', to='Voyage.gare')),
            ],
            options={
                'verbose_name': 'Itineraire',
            },
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id_planning', models.AutoField(primary_key=True, serialize=False)),
                ('date_depart', models.DateTimeField()),
                ('date_arrivee', models.DateTimeField()),
                ('place_disponible', models.IntegerField()),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('itineraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voyage.itineraire')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cooperative.transport')),
            ],
            options={
                'verbose_name': 'Planning',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id_reservation', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('nbre_place', models.IntegerField()),
                ('total_tarif', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.client')),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voyage.planning')),
            ],
            options={
                'verbose_name': 'Reservation',
            },
        ),
    ]
