# Generated by Django 5.0.4 on 2024-10-06 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voyage', '0006_ville_img_gare'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ville',
            old_name='img_gare',
            new_name='img_ville',
        ),
    ]
